/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medi.ui;

import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import medi.nf.BD;
import medi.nf.DM;
import medi.nf.Medecin;
import medi.nf.Observation;
import medi.nf.OperationInfirmiere;
import medi.nf.Patient;
import medi.nf.Prescription;
import medi.nf.Resultat;

/**
 *
 * @author CRISTANTE
 */
public class EditerDMMT extends javax.swing.JFrame {

    /**
     * Creates new form AfficherDetailDM
     */
    BD connect;
    DM dm;
    Patient p;
    ArrayList<Prescription> pres;
    ArrayList<Observation> obs;
    ArrayList<Resultat> res;
    ArrayList<OperationInfirmiere> opinf;
    Medecin m;

    public EditerDMMT(DM dm, Medecin m) {
        this.m = m;
        initComponents();
        
        DefaultTableModel resultobs = (DefaultTableModel) addobsTable.getModel();
        DefaultTableModel resultres = (DefaultTableModel) resTable.getModel();
        SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy");
        
        this.dm = dm;
        connect = new BD();
        p = dm.getP();
        //Récupération des opérations liées au DM
        obs = connect.getObservation(dm.getIddm());
        res = connect.getResultat(dm.getIddm());
        
        //Affichage de l'identité du patient
        if (p.getSexe().equals("Femme")) {
            idpat.setText(p.getNom() + " " + p.getPrenom() + " - Née le " + format.format(p.getDate()));
        } else {
            idpat.setText(p.getNom() + " " + p.getPrenom() + " - Né le " + format.format(p.getDate()));
        }
        date.setText(dm.getDate().toString());
        medref.setText(dm.getMedref().getNom() + " " + dm.getMedref().getPrenom() + " - " + dm.getMedref().getSpecialite());
        iddm.setText(String.valueOf(dm.getIddm()));



        //Affichage des résultats liés au DM dans deux tableaux
        for (int i = 0; i < res.size(); i++) {
            resultres.addRow(new Object[]{res.get(i).getDemande(),res.get(i).getDateDemande(),res.get(i).getMt().getNom() + " " + res.get(i).getMt().getPrenom() + " - " + res.get(i).getMt().getSpecialite(),res.get(i).getResultat(), res.get(i).getDateResultat(), res.get(i).getPrescripteur().getNom() + " " + res.get(i).getPrescripteur().getPrenom() + " - " + res.get(i).getPrescripteur().getSpecialite()});
        }

        resTable.setModel(resultres);
        resTable.repaint();



        //Affichage des observations liées au DM dans deux tableaux
        for (int i = 0; i < obs.size(); i++) {
            resultobs.addRow(new Object[]{obs.get(i).getObservation(), obs.get(i).getDate(), obs.get(i).getPrescripteur().getNom() + " " + obs.get(i).getPrescripteur().getPrenom() + " - " + obs.get(i).getPrescripteur().getSpecialite()});
        }
        addobsTable.setModel(resultobs);
        addobsTable.repaint();
        obsTable.setModel(resultobs);
        obsTable.repaint();

        obsPanel.add(noaddobs, "PasAjouter");
        resPanel.add(noaddres, "PasAjouter");
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
        pack();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addobs = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        addobsTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        obsArea = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        noaddobs = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        obsTable = new javax.swing.JTable();
        noaddres = new javax.swing.JPanel();
        jScrollPane17 = new javax.swing.JScrollPane();
        resTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        date = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        medref = new javax.swing.JLabel();
        nomField1 = new javax.swing.JLabel();
        nomField2 = new javax.swing.JLabel();
        nomField4 = new javax.swing.JLabel();
        iddm = new javax.swing.JLabel();
        idpat = new javax.swing.JLabel();
        nomField3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        iddm1 = new javax.swing.JLabel();
        Résultats = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        obsPanel = new javax.swing.JPanel();
        resPanel = new javax.swing.JPanel();

        addobsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Observation", "Date", "Médecin prescripteur"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(addobsTable);

        obsArea.setColumns(20);
        obsArea.setRows(5);
        jScrollPane5.setViewportView(obsArea);

        jButton3.setText("Ajouter l'observation");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addobsLayout = new javax.swing.GroupLayout(addobs);
        addobs.setLayout(addobsLayout);
        addobsLayout.setHorizontalGroup(
            addobsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        addobsLayout.setVerticalGroup(
            addobsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addobsLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        obsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Observation", "Date", "Médecin prescripteur"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(obsTable);

        javax.swing.GroupLayout noaddobsLayout = new javax.swing.GroupLayout(noaddobs);
        noaddobs.setLayout(noaddobsLayout);
        noaddobsLayout.setHorizontalGroup(
            noaddobsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        noaddobsLayout.setVerticalGroup(
            noaddobsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        resTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Demande", "Date de demande", "Médecin demandeur", "Résultat", "Date de résultat", "Médecin MT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane17.setViewportView(resTable);

        javax.swing.GroupLayout noaddresLayout = new javax.swing.GroupLayout(noaddres);
        noaddres.setLayout(noaddresLayout);
        noaddresLayout.setHorizontalGroup(
            noaddresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        noaddresLayout.setVerticalGroup(
            noaddresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(250, 250, 250));

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        date.setForeground(new java.awt.Color(102, 102, 102));
        date.setText("date");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medi/ui/images/ppth.jpg"))); // NOI18N

        medref.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        medref.setForeground(new java.awt.Color(102, 102, 102));
        medref.setText("medref");

        nomField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomField1.setForeground(new java.awt.Color(102, 102, 102));
        nomField1.setText("Dossier Médical de");

        nomField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomField2.setForeground(new java.awt.Color(102, 102, 102));
        nomField2.setText("Date :");

        nomField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomField4.setForeground(new java.awt.Color(102, 102, 102));
        nomField4.setText("ID du DM : ");

        iddm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        iddm.setForeground(new java.awt.Color(102, 102, 102));
        iddm.setText("iddm");

        idpat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idpat.setForeground(new java.awt.Color(102, 102, 102));
        idpat.setText("jLabel1");

        nomField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomField3.setForeground(new java.awt.Color(102, 102, 102));
        nomField3.setText("Médecin référent :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nomField4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iddm)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nomField1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idpat))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nomField2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nomField3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(medref)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idpat)
                            .addComponent(nomField1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomField2)
                            .addComponent(date))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomField3)
                            .addComponent(medref)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomField4)
                    .addComponent(iddm))
                .addContainerGap())
        );

        iddm1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        iddm1.setForeground(new java.awt.Color(102, 102, 102));
        iddm1.setText("Observations");

        Résultats.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Résultats.setForeground(new java.awt.Color(102, 102, 102));
        Résultats.setText("Résultat");

        jButton1.setText("Fermer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medi/ui/images/ajouter-icone-5107-16.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        obsPanel.setLayout(new java.awt.CardLayout());

        resPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 706, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(resPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(iddm1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(obsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Résultats, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iddm1)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(obsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Résultats)
                .addGap(5, 5, 5)
                .addComponent(resPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Ajouter une nouvelle observation au DM
        int ph = m.getId_user();
        int iddm = dm.getIddm();
        java.sql.Date date = new java.sql.Date(Calendar.getInstance().getTime().getTime());
        try {
            if (obsArea.getText().length() != 0) {
                ArrayList<String> obs = new ArrayList<String>();
                for (String s : obsArea.getText().split("\n")) {
                    obs.add(s);
                }
                for (int i = 0; i < obs.size(); i++) {
                    connect.genererIDObs();
                    connect.ajouterObs(connect.genererIDObs(dm), ph, obs.get(i), iddm);
                }
            }

            //Mettre à jour les tableaux des observations
            DefaultTableModel resultobs = (DefaultTableModel) addobsTable.getModel();
            resultobs.setRowCount(0);
            obs = connect.getObservation(dm.getIddm());
            for (int i = 0; i < obs.size(); i++) {
                resultobs.addRow(new Object[]{obs.get(i).getObservation(), obs.get(i).getDate(), obs.get(i).getPrescripteur().getNom() + " " + obs.get(i).getPrescripteur().getPrenom() + " - " + obs.get(i).getPrescripteur().getSpecialite()});
            }
            addobsTable.setModel(resultobs);
            addobsTable.repaint();
            obsTable.setModel(resultobs);
            obsTable.repaint();
            obsPanel.remove(addobs);
            obsPanel.add(noaddobs, "PasAjouter");
            CardLayout cardLayout = (CardLayout) obsPanel.getLayout();
            cardLayout.show(obsPanel, "PasAjouter");
            jToggleButton1.setSelected(false);
            pack();
            obsArea.setText(null);
            javax.swing.JOptionPane.showMessageDialog(null, "Observation ajoutée au DM.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(null, "Erreur : cette observation n'a pas pu être ajoutée au DM.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (jToggleButton1.isSelected()) {
            obsPanel.remove(noaddobs);
            obsPanel.add(addobs, "Ajouter");
            CardLayout cardLayout = (CardLayout) obsPanel.getLayout();
            cardLayout.show(obsPanel, "Ajouter");
            pack();
        } else {
            obsPanel.remove(addobs);
            obsPanel.add(noaddobs, "PasAjouter");
            CardLayout cardLayout = (CardLayout) obsPanel.getLayout();
            cardLayout.show(obsPanel, "PasAjouter");
            pack();
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditerDMMT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditerDMMT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditerDMMT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditerDMMT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Résultats;
    private javax.swing.JPanel addobs;
    private javax.swing.JTable addobsTable;
    private javax.swing.JLabel date;
    private javax.swing.JLabel iddm;
    private javax.swing.JLabel iddm1;
    private javax.swing.JLabel idpat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel medref;
    private javax.swing.JPanel noaddobs;
    private javax.swing.JPanel noaddres;
    private javax.swing.JLabel nomField1;
    private javax.swing.JLabel nomField2;
    private javax.swing.JLabel nomField3;
    private javax.swing.JLabel nomField4;
    private javax.swing.JTextArea obsArea;
    private javax.swing.JPanel obsPanel;
    private javax.swing.JTable obsTable;
    private javax.swing.JPanel resPanel;
    private javax.swing.JTable resTable;
    // End of variables declaration//GEN-END:variables
}
